name: Congratulate Contributors

on:
  pull_request:
    types: [closed]

permissions:
  pull-requests: write

jobs:
  congratulate:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch contributor data and comment
        uses: actions/github-script@v5
        with:
          script: |
            const allPRs = await github.paginate(github.rest.pulls.list, {
            owner: 'twentyhq',
            repo: 'twenty',
            state: 'closed',
            per_page: 100
            }, (response) => response.data.filter(pr => pr.merged_at));
            console.log('All Merged PRs:', allPRs.length);


            const contributionsCount = allPRs.reduce((acc, pr) => {
            const author = pr.user.login;
            if (!['dependabot',
            'cyborch',
            'emilienchvt',
            'Samox',
            'charlesBochet',
            'gitstart-app',
            'thaisguigon',
            'lucasbordeau',
            'magrinj',
            'Weiko',
            'gitstart-twenty',
            'bosiraphael',
            'martmull',
            'FelixMalfait',
            'thomtrp',
            'Bonapara',
            'nimraahmed'].includes(author)) {
              acc[author] = (acc[author] || 0) + 1;
              }
            return acc;
            }, {});

            console.log('contributorsCount', contributionsCount.length);

            const sortedContributors = Object.entries(contributionsCount)
            .map(([author, count]) => ({ author, count }))
            .sort((a, b) => b.count - a.count);

            console.log('sorted', sortedContributors.length);


            const userName = 'Kanav-Arora';
            const userContributionCount = contributionsCount[userName] || 0;
            const userRank = sortedContributors.findIndex(con => con.author === userName) + 1;
            console.log('userRank', userRank.length);
            const rankPercentage = Math.ceil(userRank / sortedContributors.length * 100);
            const contributorUrl = `https://twenty.com/contributors/${userName}`;

            const message = `Thanks @${userName} for your contribution!\n` +
                            `This marks your ${userContributionCount}th PR on the repo. ` +
                            `You're top ${rankPercentage.toFixed(0)}% of all our contributors 🎉\n` +
                            `[See contributor page](${contributorUrl}) - ` +
                            `[Share on LinkedIn](https://www.linkedin.com/sharing/share-offsite/?url=${contributorUrl}) - ` +
                            `[Share on Twitter](https://www.twitter.com/share?url=${contributorUrl})`
                
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: message
            });
