name: Congratulate Contributors

on:
  pull_request:
    types: [closed]

permissions:
  pull-requests: write

jobs:
  congratulate:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch contributor data and comment
        uses: actions/github-script@v7
        with:
          script: |
            const userName = context.actor;

            async function fetchContributorStats(username) {
              const apiUrl = `https://twenty.ngrok.app/api/contributors/contributorStats/${username}`;
             
              try {
                const response = await fetch(apiUrl);
                const data = await response.json();

                console.log(data);
                
                return data;
              } catch (error) {
                console.error('Error fetching contributor stats:', error);
                throw error;
              }
            }

            async function run() {
              try {
                const stats = await fetchContributorStats(userName);
                const contributorUrl = `https://twenty.com/contributors/${userName}`;

            const message = `Thanks @${userName} for your contribution!\n` +
                            `This marks your ${stats.mergedPRsCount}th PR on the repo. ` +
                            `You're top ${stats.rank}% of all our contributors 🎉\n` +
                            `[See contributor page](${contributorUrl}) - ` +
                            `[Share on LinkedIn](https://www.linkedin.com/sharing/share-offsite/?url=${contributorUrl}) - ` +
                            `[Share on Twitter](https://www.twitter.com/share?url=${contributorUrl})`
                
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: message
            });
              } catch (error) {
                console.error('Failed to handle PR merge:', error);
              }
            }

            run();
